SELECT PLAYER.NAME AS PLAYER_NAME,BASE_STATISTIC.NAME AS STATISTIC_NAME,SUM(STATISTICS_PLAYER_MATCH_FACT.VALUE)  AS VALUE
FROM ((STATISTICS_PLAYER_MATCH_FACT INNER JOIN PLAYER ON PLAYER.idPLAYER = STATISTICS_PLAYER_MATCH_FACT.idPLAYER ) 
INNER JOIN BASE_STATISTIC ON BASE_STATISTIC.idBASE_STATISTIC = STATISTICS_PLAYER_MATCH_FACT.idBASE_STATISTIC) 
GROUP BY PLAYER.NAME, BASE_STATISTIC.NAME