SELECT PLAYER.NAME AS PLAYER_NAME,BASE_STATISTIC.NAME AS STATISTIC_NAME,SUM(STATISTICS_PLAYER_MATCH_FACT.VALUE)  AS VALUE
FROM ((STATISTICS_PLAYER_MATCH_FACT INNER JOIN PLAYER ON PLAYER.idPLAYER = STATISTICS_PLAYER_MATCH_FACT.idPLAYER ) 
INNER JOIN BASE_STATISTIC ON BASE_STATISTIC.idBASE_STATISTIC = STATISTICS_PLAYER_MATCH_FACT.idBASE_STATISTIC) 
GROUP BY PLAYER.NAME, BASE_STATISTIC.NAME

UNION ALL


SELECT PLAYER_NAME,STATISTIC_NAME, IF(DENOMINATOR_VALUE!=0,NUMERATOR_VALUE/DENOMINATOR_VALUE,0) AS VALUE FROM
(SELECT PLAYER.NAME AS PLAYER_NAME,RATIO_STATISTIC.NAME as STATISTIC_NAME,PLAYER.idPLAYER,RATIO_STATISTIC.NUMERATOR,RATIO_STATISTIC.DENOMINATOR, 
	SUM(STATISTICS_PLAYER_MATCH_FACT.VALUE) AS NUMERATOR_VALUE FROM 
(STATISTICS_PLAYER_MATCH_FACT 
	INNER JOIN RATIO_STATISTIC ON RATIO_STATISTIC.NUMERATOR = STATISTICS_PLAYER_MATCH_FACT.idBASE_STATISTIC)
    INNER JOIN PLAYER ON PLAYER.idPLAYER = STATISTICS_PLAYER_MATCH_FACT.idPLAYER
    GROUP BY PLAYER.idPLAYER, RATIO_STATISTIC.NUMERATOR,RATIO_STATISTIC.DENOMINATOR) T1
INNER JOIN
(SELECT PLAYER.idPLAYER,RATIO_STATISTIC.NUMERATOR,RATIO_STATISTIC.DENOMINATOR, 
	SUM(STATISTICS_PLAYER_MATCH_FACT.VALUE) AS DENOMINATOR_VALUE FROM 
(STATISTICS_PLAYER_MATCH_FACT 
	INNER JOIN RATIO_STATISTIC ON RATIO_STATISTIC.DENOMINATOR = STATISTICS_PLAYER_MATCH_FACT.idBASE_STATISTIC)
    INNER JOIN PLAYER ON PLAYER.idPLAYER = STATISTICS_PLAYER_MATCH_FACT.idPLAYER
    GROUP BY PLAYER.idPLAYER, RATIO_STATISTIC.NUMERATOR,RATIO_STATISTIC.DENOMINATOR) T2 ON T1.idPLAYER = T2.idPLAYER AND T1.NUMERATOR = T2.NUMERATOR AND T1.DENOMINATOR=T2.DENOMINATOR
  